version: "3.7"

services:
  couchdb:
    image: couchdb:3.2.2
    ports:
      - 5984:5984
    volumes:
      - couchdb-volume:/opt/couchdb/data
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"

volumes:
  couchdb-volume:
