import pytest
import ipdb
import jw.txt
# import jw.csv
from jw.csv import create_csv
from jw import Phone


@pytest.mark.skip
def test_get_items_from_csv():
    # ipdb.set_trace()
    items = jw.csv.get_items_from_csv('./data/csv/quebradillas_1.csv')
    print(items)
    assert len(items) > 0


@pytest.mark.csv
@pytest.mark.parametrize("territory", [
    (r'./data/txt/import/arecibo/arecibo-a.txt'),
    (r'./data/txt/import/arecibo/arecibo-b.txt'),
    (r'./data/txt/import/arecibo/arecibo-c.txt'),
    (r'./data/txt/import/arecibo/arecibo-d.txt'),
    (r'./data/txt/import/arecibo/arecibo-e.txt'),
    (r'./data/txt/import/arecibo/arecibo-f.txt'),
    (r'./data/txt/import/arecibo/arecibo-g.txt'),
    (r'./data/txt/import/arecibo/arecibo-h.txt'),
    (r'./data/txt/import/arecibo/arecibo-i.txt'),
    (r'./data/txt/import/arecibo/arecibo-j.txt'),
    (r'./data/txt/import/arecibo/arecibo-k.txt'),
    (r'./data/txt/import/arecibo/arecibo-l.txt'),
    (r'./data/txt/import/arecibo/arecibo-m.txt'),
    (r'./data/txt/import/arecibo/arecibo-n.txt'),
    (r'./data/txt/import/arecibo/arecibo-o.txt'),
    (r'./data/txt/import/arecibo/arecibo-p.txt'),
    (r'./data/txt/import/arecibo/arecibo-q.txt'),
    (r'./data/txt/import/arecibo/arecibo-r.txt'),
    (r'./data/txt/import/arecibo/arecibo-s.txt'),
    (r'./data/txt/import/arecibo/arecibo-t.txt'),
    (r'./data/txt/import/arecibo/arecibo-v.txt'),
    (r'./data/txt/import/arecibo/arecibo-w.txt'),
    (r'./data/txt/import/arecibo/arecibo-z.txt'),
    (r'./data/txt/import/hatillo/hatillo-a.txt'),
    (r'./data/txt/import/hatillo/hatillo-b.txt'),
    (r'./data/txt/import/hatillo/hatillo-c.txt'),
    (r'./data/txt/import/hatillo/hatillo-d.txt'),
    (r'./data/txt/import/hatillo/hatillo-e.txt'),
    (r'./data/txt/import/hatillo/hatillo-f.txt'),
    (r'./data/txt/import/hatillo/hatillo-g.txt'),
    (r'./data/txt/import/hatillo/hatillo-h.txt'),
    (r'./data/txt/import/hatillo/hatillo-i.txt'),
    (r'./data/txt/import/hatillo/hatillo-j.txt'),
    (r'./data/txt/import/hatillo/hatillo-k.txt'),
    (r'./data/txt/import/hatillo/hatillo-l.txt'),
    (r'./data/txt/import/hatillo/hatillo-m.txt'),
    (r'./data/txt/import/hatillo/hatillo-n.txt'),
    (r'./data/txt/import/hatillo/hatillo-o.txt'),
    (r'./data/txt/import/hatillo/hatillo-p.txt'),
    (r'./data/txt/import/hatillo/hatillo-r.txt'),
    (r'./data/txt/import/hatillo/hatillo-s.txt'),
    (r'./data/txt/import/hatillo/hatillo-t.txt'),
    (r'./data/txt/import/hatillo/hatillo-u.txt'),
    (r'./data/txt/import/hatillo/hatillo-w.txt'),
    (r'./data/txt/import/hatillo/hatillo-x.txt'),
    (r'./data/txt/import/hatillo/hatillo-z.txt'),
    (r'./data/txt/import/camuy/camuy-a.txt'),
    (r'./data/txt/import/camuy/camuy-b.txt'),
    (r'./data/txt/import/camuy/camuy-c.txt'),
    (r'./data/txt/import/camuy/camuy-d.txt'),
    (r'./data/txt/import/camuy/camuy-e.txt'),
    (r'./data/txt/import/camuy/camuy-f.txt'),
    (r'./data/txt/import/camuy/camuy-g.txt'),
    (r'./data/txt/import/camuy/camuy-h.txt'),
    (r'./data/txt/import/camuy/camuy-i.txt'),
    (r'./data/txt/import/camuy/camuy-j.txt'),
    (r'./data/txt/import/camuy/camuy-k.txt'),
    (r'./data/txt/import/camuy/camuy-m.txt'),
    (r'./data/txt/import/camuy/camuy-n.txt'),
    # (r'./data/txt/import/camuy/camuy-o.txt'),
    (r'./data/txt/import/camuy/camuy-p.txt'),
    (r'./data/txt/import/camuy/camuy-q.txt'),
    (r'./data/txt/import/camuy/camuy-r.txt'),
    (r'./data/txt/import/camuy/camuy-s.txt'),
    (r'./data/txt/import/camuy/camuy-r.txt'),
    (r'./data/txt/import/camuy/camuy-u.txt'),
    (r'./data/txt/import/camuy/camuy-v.txt'),
    (r'./data/txt/import/camuy/camuy-w.txt'),
    (r'./data/txt/import/camuy/camuy-x.txt'),
    (r'./data/txt/import/camuy/camuy-y.txt'),
    (r'./data/txt/import/camuy/camuy-z.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-a.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-b.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-c.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-d.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-e.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-f.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-g.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-h.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-i.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-j.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-k.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-l.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-m.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-n.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-o.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-p.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-r.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-s.txt'),
    (r'./data/txt/import/quebradillas/quebradillas-z.txt'),
])
def test_extract_phone(territory):
    phones = jw.txt.extract_phone(
        territory)

    assert len(phones) > 0

    for phone in phones:
        assert isinstance(phone, Phone)
        # print(phone)

    print(territory)
    print(f"phones size: {len(phones)}")


@pytest.mark.csv
@pytest.mark.parametrize("params", [
    (r'./data/txt/import/arecibo/arecibo-a.txt',
     r'./data/csv/export/arecibo/arecibo-a.csv',
     'arecibo-a'),
    (r'./data/txt/import/arecibo/arecibo-b.txt',
     r'./data/csv/export/arecibo/arecibo-b.csv',
     'arecibo-b'),
    (r'./data/txt/import/arecibo/arecibo-c.txt',
     r'./data/csv/export/arecibo/arecibo-c.csv',
     'arecibo-c'),
    (r'./data/txt/import/arecibo/arecibo-d.txt',
     r'./data/csv/export/arecibo/arecibo-d.csv',
     'arecibo-d'),
    (r'./data/txt/import/arecibo/arecibo-e.txt',
     r'./data/csv/export/arecibo/arecibo-e.csv',
     'arecibo-e'),
    (r'./data/txt/import/arecibo/arecibo-f.txt',
     r'./data/csv/export/arecibo/arecibo-f.csv',
     'arecibo-f'),
    (r'./data/txt/import/arecibo/arecibo-g.txt',
     r'./data/csv/export/arecibo/arecibo-g.csv',
     'arecibo-g'),
    (r'./data/txt/import/arecibo/arecibo-h.txt',
     r'./data/csv/export/arecibo/arecibo-h.csv',
     'arecibo-h'),
    (r'./data/txt/import/arecibo/arecibo-i.txt',
     r'./data/csv/export/arecibo/arecibo-i.csv',
     'arecibo-i'),
    (r'./data/txt/import/arecibo/arecibo-j.txt',
     r'./data/csv/export/arecibo/arecibo-j.csv',
     'arecibo-j'),
    (r'./data/txt/import/arecibo/arecibo-k.txt',
     r'./data/csv/export/arecibo/arecibo-k.csv',
     'arecibo-k'),
    (r'./data/txt/import/arecibo/arecibo-l.txt',
     r'./data/csv/export/arecibo/arecibo-l.csv',
     'arecibo-l'),
    (r'./data/txt/import/arecibo/arecibo-m.txt',
     r'./data/csv/export/arecibo/arecibo-m.csv',
     'arecibo-m'),
    (r'./data/txt/import/arecibo/arecibo-n.txt',
     r'./data/csv/export/arecibo/arecibo-n.csv',
     'arecibo-n'),
    (r'./data/txt/import/arecibo/arecibo-o.txt',
     r'./data/csv/export/arecibo/arecibo-o.csv',
     'arecibo-o'),
    (r'./data/txt/import/arecibo/arecibo-p.txt',
     r'./data/csv/export/arecibo/arecibo-p.csv',
     'arecibo-p'),
    (r'./data/txt/import/arecibo/arecibo-q.txt',
     r'./data/csv/export/arecibo/arecibo-q.csv',
     'arecibo-q'),
    (r'./data/txt/import/arecibo/arecibo-r.txt',
     r'./data/csv/export/arecibo/arecibo-r.csv',
     'arecibo-r'),
    (r'./data/txt/import/arecibo/arecibo-s.txt',
     r'./data/csv/export/arecibo/arecibo-s.csv',
     'arecibo-s'),
    (r'./data/txt/import/arecibo/arecibo-t.txt',
     r'./data/csv/export/arecibo/arecibo-t.csv',
     'arecibo-t'),
    (r'./data/txt/import/arecibo/arecibo-v.txt',
     r'./data/csv/export/arecibo/arecibo-v.csv',
     'arecibo-v'),
    (r'./data/txt/import/arecibo/arecibo-w.txt',
     r'./data/csv/export/arecibo/arecibo-w.csv',
     'arecibo-w'),
    (r'./data/txt/import/arecibo/arecibo-z.txt',
     r'./data/csv/export/arecibo/arecibo-z.csv',
     'arecibo-z'),
    (r'./data/txt/import/hatillo/hatillo-a.txt',
     r'./data/csv/export/hatillo/hatillo-a.csv',
     'hatillo-a'),
    (r'./data/txt/import/hatillo/hatillo-b.txt',
     r'./data/csv/export/hatillo/hatillo-b.csv',
     'hatillo-b'),
    (r'./data/txt/import/hatillo/hatillo-c.txt',
     r'./data/csv/export/hatillo/hatillo-c.csv',
     'hatillo-c'),
    (r'./data/txt/import/hatillo/hatillo-d.txt',
     r'./data/csv/export/hatillo/hatillo-d.csv',
     'hatillo-d'),
    (r'./data/txt/import/hatillo/hatillo-e.txt',
     r'./data/csv/export/hatillo/hatillo-e.csv',
     'hatillo-e'),
    (r'./data/txt/import/hatillo/hatillo-f.txt',
     r'./data/csv/export/hatillo/hatillo-f.csv',
     'hatillo-f'),
    (r'./data/txt/import/hatillo/hatillo-g.txt',
     r'./data/csv/export/hatillo/hatillo-g.csv',
     'hatillo-g'),
    (r'./data/txt/import/hatillo/hatillo-h.txt',
     r'./data/csv/export/hatillo/hatillo-h.csv',
     'hatillo-h'),
    (r'./data/txt/import/hatillo/hatillo-i.txt',
     r'./data/csv/export/hatillo/hatillo-i.csv',
     'hatillo-i'),
    (r'./data/txt/import/hatillo/hatillo-j.txt',
     r'./data/csv/export/hatillo/hatillo-j.csv',
     'hatillo-j'),
    (r'./data/txt/import/hatillo/hatillo-k.txt',
     r'./data/csv/export/hatillo/hatillo-k.csv',
     'hatillo-k'),
    (r'./data/txt/import/hatillo/hatillo-l.txt',
     r'./data/csv/export/hatillo/hatillo-l.csv',
     'hatillo-l'),
    (r'./data/txt/import/hatillo/hatillo-m.txt',
     r'./data/csv/export/hatillo/hatillo-m.csv',
     'hatillo-m'),
    (r'./data/txt/import/hatillo/hatillo-n.txt',
     r'./data/csv/export/hatillo/hatillo-n.csv',
     'hatillo-n'),
    (r'./data/txt/import/hatillo/hatillo-o.txt',
     r'./data/csv/export/hatillo/hatillo-o.csv',
     'hatillo-o'),
    (r'./data/txt/import/hatillo/hatillo-p.txt',
     r'./data/csv/export/hatillo/hatillo-p.csv',
     'hatillo-p'),
    (r'./data/txt/import/hatillo/hatillo-r.txt',
     r'./data/csv/export/hatillo/hatillo-r.csv',
     'hatillo-r'),
    (r'./data/txt/import/hatillo/hatillo-s.txt',
     r'./data/csv/export/hatillo/hatillo-s.csv',
     'hatillo-s'),
    (r'./data/txt/import/hatillo/hatillo-t.txt',
     r'./data/csv/export/hatillo/hatillo-t.csv',
     'hatillo-t'),
    (r'./data/txt/import/hatillo/hatillo-u.txt',
     r'./data/csv/export/hatillo/hatillo-u.csv',
     'hatillo-u'),
    (r'./data/txt/import/hatillo/hatillo-w.txt',
     r'./data/csv/export/hatillo/hatillo-w.csv',
     'hatillo-w'),
    (r'./data/txt/import/hatillo/hatillo-x.txt',
     r'./data/csv/export/hatillo/hatillo-x.csv',
     'hatillo-x'),
    (r'./data/txt/import/hatillo/hatillo-z.txt',
     r'./data/csv/export/hatillo/hatillo-z.csv',
     'hatillo-z'),
    (r'./data/txt/import/camuy/camuy-a.txt',
     r'./data/csv/export/camuy/camuy-a.csv',
     'camuy-a'),
    (r'./data/txt/import/camuy/camuy-b.txt',
     r'./data/csv/export/camuy/camuy-b.csv',
     'camuy-b'),
    (r'./data/txt/import/camuy/camuy-c.txt',
     r'./data/csv/export/camuy/camuy-c.csv',
     'camuy-c'),
    (r'./data/txt/import/camuy/camuy-d.txt',
     r'./data/csv/export/camuy/camuy-d.csv',
     'camuy-d'),
    (r'./data/txt/import/camuy/camuy-e.txt',
     r'./data/csv/export/camuy/camuy-e.csv',
     'camuy-e'),
    (r'./data/txt/import/camuy/camuy-f.txt',
     r'./data/csv/export/camuy/camuy-f.csv',
     'camuy-f'),
    (r'./data/txt/import/camuy/camuy-g.txt',
     r'./data/csv/export/camuy/camuy-g.csv',
     'camuy-g'),
    (r'./data/txt/import/camuy/camuy-h.txt',
     r'./data/csv/export/camuy/camuy-h.csv',
     'camuy-h'),
    (r'./data/txt/import/camuy/camuy-i.txt',
     r'./data/csv/export/camuy/camuy-i.csv',
     'camuy-i'),
    (r'./data/txt/import/camuy/camuy-j.txt',
     r'./data/csv/export/camuy/camuy-j.csv',
     'camuy-j'),
    (r'./data/txt/import/camuy/camuy-k.txt',
     r'./data/csv/export/camuy/camuy-k.csv',
     'camuy-k'),
    (r'./data/txt/import/camuy/camuy-l.txt',
     r'./data/csv/export/camuy/camuy-l.csv',
     'camuy-l'),
    (r'./data/txt/import/camuy/camuy-m.txt',
     r'./data/csv/export/camuy/camuy-m.csv',
     'camuy-m'),
    (r'./data/txt/import/camuy/camuy-n.txt',
     r'./data/csv/export/camuy/camuy-n.csv',
     'camuy-n'),
    # (r'./data/txt/import/camuy/camuy-o.txt',
    #  r'./data/csv/export/camuy/camuy-o.csv',
    #  'camuy-o'),
    (r'./data/txt/import/camuy/camuy-p.txt',
     r'./data/csv/export/camuy/camuy-p.csv',
     'camuy-p'),
    (r'./data/txt/import/camuy/camuy-q.txt',
     r'./data/csv/export/camuy/camuy-q.csv',
     'camuy-q'),
    (r'./data/txt/import/camuy/camuy-r.txt',
     r'./data/csv/export/camuy/camuy-r.csv',
     'camuy-r'),
    (r'./data/txt/import/camuy/camuy-s.txt',
     r'./data/csv/export/camuy/camuy-s.csv',
     'camuy-s'),
    (r'./data/txt/import/camuy/camuy-t.txt',
     r'./data/csv/export/camuy/camuy-t.csv',
     'camuy-t'),
    (r'./data/txt/import/camuy/camuy-u.txt',
     r'./data/csv/export/camuy/camuy-u.csv',
     'camuy-u'),
    (r'./data/txt/import/camuy/camuy-v.txt',
     r'./data/csv/export/camuy/camuy-v.csv',
     'camuy-v'),
    (r'./data/txt/import/camuy/camuy-w.txt',
     r'./data/csv/export/camuy/camuy-w.csv',
     'camuy-w'),
    (r'./data/txt/import/camuy/camuy-x.txt',
     r'./data/csv/export/camuy/camuy-x.csv',
     'camuy-x'),
    (r'./data/txt/import/camuy/camuy-y.txt',
     r'./data/csv/export/camuy/camuy-y.csv',
     'camuy-y'),
    (r'./data/txt/import/camuy/camuy-z.txt',
     r'./data/csv/export/camuy/camuy-z.csv',
     'camuy-z'),
    (r'./data/txt/import/quebradillas/quebradillas-a.txt',
     r'./data/csv/export/quebradillas/quebradillas-a.csv',
     'quebradillas-a'),
    (r'./data/txt/import/quebradillas/quebradillas-b.txt',
     r'./data/csv/export/quebradillas/quebradillas-b.csv',
     'quebradillas-b'),
    (r'./data/txt/import/quebradillas/quebradillas-c.txt',
     r'./data/csv/export/quebradillas/quebradillas-c.csv',
     'quebradillas-c'),
    (r'./data/txt/import/quebradillas/quebradillas-d.txt',
     r'./data/csv/export/quebradillas/quebradillas-d.csv',
     'quebradillas-d'),
    (r'./data/txt/import/quebradillas/quebradillas-e.txt',
     r'./data/csv/export/quebradillas/quebradillas-e.csv',
     'quebradillas-e'),
    (r'./data/txt/import/quebradillas/quebradillas-f.txt',
     r'./data/csv/export/quebradillas/quebradillas-f.csv',
     'quebradillas-f'),
    (r'./data/txt/import/quebradillas/quebradillas-g.txt',
     r'./data/csv/export/quebradillas/quebradillas-g.csv',
     'quebradillas-g'),
    (r'./data/txt/import/quebradillas/quebradillas-h.txt',
     r'./data/csv/export/quebradillas/quebradillas-h.csv',
     'quebradillas-h'),
    (r'./data/txt/import/quebradillas/quebradillas-i.txt',
     r'./data/csv/export/quebradillas/quebradillas-i.csv',
     'quebradillas-i'),
    (r'./data/txt/import/quebradillas/quebradillas-j.txt',
     r'./data/csv/export/quebradillas/quebradillas-j.csv',
     'quebradillas-j'),
    (r'./data/txt/import/quebradillas/quebradillas-k.txt',
     r'./data/csv/export/quebradillas/quebradillas-k.csv',
     'quebradillas-k'),
    (r'./data/txt/import/quebradillas/quebradillas-l.txt',
     r'./data/csv/export/quebradillas/quebradillas-l.csv',
     'quebradillas-l'),
    (r'./data/txt/import/quebradillas/quebradillas-m.txt',
     r'./data/csv/export/quebradillas/quebradillas-m.csv',
     'quebradillas-m'),
    (r'./data/txt/import/quebradillas/quebradillas-n.txt',
     r'./data/csv/export/quebradillas/quebradillas-n.csv',
     'quebradillas-n'),
    (r'./data/txt/import/quebradillas/quebradillas-o.txt',
     r'./data/csv/export/quebradillas/quebradillas-o.csv',
     'quebradillas-o'),
    (r'./data/txt/import/quebradillas/quebradillas-p.txt',
     r'./data/csv/export/quebradillas/quebradillas-p.csv',
     'quebradillas-p'),
    (r'./data/txt/import/quebradillas/quebradillas-r.txt',
     r'./data/csv/export/quebradillas/quebradillas-r.csv',
     'quebradillas-r'),
    (r'./data/txt/import/quebradillas/quebradillas-s.txt',
     r'./data/csv/export/quebradillas/quebradillas-s.csv',
     'quebradillas-s'),
    (r'./data/txt/import/quebradillas/quebradillas-z.txt',
     r'./data/csv/export/quebradillas/quebradillas-z.csv',
     'quebradillas-z'),
])
def test_create_csv(params):
    (txt, path, territory) = params
    phones = jw.txt.extract_phone(txt)

    assert len(phones) > 0

    for phone in phones:
        assert isinstance(phone, Phone)

    print(territory)
    print(f"phones size: {len(phones)}")

    create_csv(phones, path, territory)
