version: "3.7"

services:
  postgres:
    image: postgres:15.4
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"

volumes:
  postgres-volume:
